<?php
return array (
  'version' => '5.1',
  'isopen' => true,
  'debug' => false,
  'domain' => '',
  'apikey' => '',
  'host' => 'localhost',
  'port' => '8000',
  'emot' => 'default',
  'theme' => 'base',
  'opacity' => '80',
  'local' => 'zh-CN',
  'show_realname' => false,
  'enable_room' => false,
  'enable_chatlink' => false,
  'enable_shortcut' => true,
  'enable_menu' => false,
  'enable_login' => false,
  'enable_noti' => true,
  'admin_uid' => '0',
  'visitor' => false,
  'show_unavailable' => false,
  'upload' => false,
);
